#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
#EXPOSE 50555

# Install procps
RUN apt-get update && apt-get install -y procps

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["WebAppDotNet6.csproj", ""]
RUN dotnet restore "./WebAppDotNet6.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebAppDotNet6.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebAppDotNet6.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

COPY tz-6 /tz-6
COPY cert-test /cert-test
COPY certsname-printer /certsname-printer
COPY update-history-util /update-history-util
COPY certificates/ /certs/
COPY kuduagent_linux_x64 /kuduagent
COPY startup /startup
COPY greeter /greeter
COPY linuxprocessenvironkeyutil /linuxprocessenvironkeyutil

ENV WEBSITE_PRIVATE_CERTS_PATH="/certs/private"
ENV WEBSITE_PUBLIC_CERTS_PATH="/certs/public"
ENV WEBSITE_INTERMEDIATE_CERTS_PATH="/certs/intermediate"
ENV WEBSITE_ROOT_CERTS_PATH="/certs/root"
COPY startuphook /startuphook
ENV DOTNET_STARTUP_HOOKS="/startuphook/StaruphookLib.dll"
ENV WEBSITE_OS=linux
ENV WEBJOB_ENV=true
ENV WEBJOB_HOME=/home
#ENV Kestrel:Endpoints:Http:Url="http://*:80"
#ENV ASPNETCORE_CONTENTROOT="/update-history-util"

ENTRYPOINT ["dotnet", "WebAppDotNet6.dll"]
#ENTRYPOINT ["bash", "/startup/startup.sh"]

# docker build . -t sratdocker/dotnet6webapplinux -f Dockerfile-linux
# expose webapp's container port 80 on host port 5001 and webjobs port 50555 on host port 5002
# docker run -p 5001:80 -p 5002:50555 docker.io/sratdocker/dotnet6webapplinux